% Generated by Python - Facts for Prolog

student('S1001', 'Hadif Idham').
student('S1002', 'Akmal').
student('S1003', 'Hezry').
student('S1004', 'Hakimi').
student('S1006', 'Faliq').

enrollment('S1001', 'CS100', 85).
enrollment('S1001', 'CS101', 90).
enrollment('S1001', 'CS102', 78).
enrollment('S1002', 'CS100', 76).
enrollment('S1002', 'CS101', 82).
enrollment('S1002', 'CS102', 81).
enrollment('S1003', 'CS100', 92).
enrollment('S1003', 'CS101', 94).
enrollment('S1003', 'CS102', 96).
enrollment('S1003', 'CS103', 91).
enrollment('S1003', 'CS104', 89).
enrollment('S1003', 'CS105', 85).
enrollment('S1003', 'CS106', 82).
enrollment('S1004', 'CS100', 88).
enrollment('S1004', 'CS101', 84).
enrollment('S1004', 'CS102', 85).
enrollment('S1004', 'CS103', 86).
enrollment('S1004', 'CS104', 90).
enrollment('S1006', 'CS100', 91).
enrollment('S1006', 'CS101', 89).
enrollment('S1006', 'CS102', 93).
enrollment('S1006', 'CS103', 88).
enrollment('S1006', 'CS104', 90).
enrollment('S1006', 'CS105', 87).
enrollment('S1006', 'CS106', 86).
enrollment('S1006', 'CS107', 85).
