% Generated by Python - Facts for Prolog
% Load with: ['python_facts.pl'].

:- dynamic student/2.
:- dynamic enrollment/3.

student('S1001', 'Hadif Idham').
student('S1002', 'Akmal').
student('S1003', 'Hezry').
student('S1004', 'Hakimi').
student('S1006', 'Faliq').

enrollment('S1001', 'CS101', 85).
enrollment('S1001', 'CS102', 90).
enrollment('S1001', 'CS103', 78).
enrollment('S1002', 'CS101', 76).
enrollment('S1002', 'CS102', 82).
enrollment('S1002', 'CS103', 81).
enrollment('S1003', 'CS101', 92).
enrollment('S1003', 'CS102', 94).
enrollment('S1003', 'CS103', 96).
enrollment('S1003', 'CS104', 91).
enrollment('S1003', 'CS105', 89).
enrollment('S1003', 'CS106', 85).
enrollment('S1003', 'CS107', 82).
enrollment('S1004', 'CS101', 88).
enrollment('S1004', 'CS102', 84).
enrollment('S1004', 'CS103', 85).
enrollment('S1004', 'CS104', 86).
enrollment('S1004', 'CS105', 90).
enrollment('S1006', 'CS101', 91).
enrollment('S1006', 'CS102', 89).
enrollment('S1006', 'CS103', 93).
enrollment('S1006', 'CS104', 88).
enrollment('S1006', 'CS105', 90).
enrollment('S1006', 'CS106', 87).
enrollment('S1006', 'CS107', 86).
enrollment('S1006', 'CS108', 85).
